# Generated by Django 2.2 on 2020-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201218_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='post',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
