# Generated by Django 2.2 on 2020-12-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201218_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='avatar-2.jpg', upload_to=''),
        ),
    ]
