# Generated by Django 2.2 on 2020-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201221_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='img/avatar-2.jpg', upload_to=''),
        ),
    ]
