# Generated by Django 2.2 on 2020-12-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201221_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='avatar-2.jpg', upload_to=''),
        ),
    ]
